[package]
name = "speed-wasm"
version = "0.1.0"
authors = ["Marina M"]
description = "calculating domination number"
license = "MIT/Apache-2.0"
repository = "https://github.com/marinamolinat/"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
